---
language: java
jdk: openjdk11
dist: xenial

git:
  depth: false
  quiet: true

cache:
  directories:
    - ${HOME}/.m2/repository

before_cache: rm -rf $HOME/.m2/repository/org/gytheio

branches:
  only:
    - master
    - /^SP\/.+$/
    - /^HF\/.+$/

stages:
  - build
  - release

before_install: bash _ci/init.sh

jobs:
  include:
    - name: "Build"
      stage: build
      script: bash _ci/build.sh

    - name: "WhiteSource"
      script: bash _ci/whitesource.sh

    - name: "Release"
      stage: release
      if: commit_message ~= /\[release\]/ AND branch ~= /^(master|SP\/.+|HF\/.+)$/
      script: bash _ci/release.sh
