
messaging:
    broker:
        url: tcp://localhost:5672
        # username: guest
        # password: password

contentReferenceHandlers:
    source:
        contentReferenceHandlerClass: org.gytheio.content.handler.FileContentReferenceHandlerImpl
        directoryPath: /tmp/gytheio
    target:
        contentReferenceHandlerClass: org.gytheio.content.handler.FileContentReferenceHandlerImpl
        directoryPath: /tmp/gytheio
#    source:
#        contentReferenceHandlerClass: org.gytheio.content.handler.webdav.WebDavContentReferenceHandlerImpl
#        remoteBaseUrl: http://localhost:8888/tmp
#        username: gytheio
#        password: gytheio
#    target:
#        contentReferenceHandlerClass: org.gytheio.content.handler.webdav.WebDavContentReferenceHandlerImpl
#        remoteBaseUrl: http://localhost:8888/tmp
#        username: gytheio
#        password: gytheio
#    source:
#        contentReferenceHandlerClass: org.gytheio.content.handler.s3.S3ContentReferenceHandlerImpl
#        s3AccessKey: <key>
#        s3SecretKey: <secret>
#        s3BucketName: gytheio
#        s3BucketRegion: US_EAST_1
#    target:
#        contentReferenceHandlerClass: org.gytheio.content.handler.s3.S3ContentReferenceHandlerImpl
#        s3AccessKey: <key>
#        s3SecretKey: <secret>
#        s3BucketName: gytheio
#        s3BucketRegion: US_EAST_1

components:
  - name: imagemagick
    workerClass: org.gytheio.content.transform.imagemagick.ImageMagickContentTransformerWorker
    enabled: true
    requestQueue: alfresco.transform.request.image
    replyQueue: alfresco.transform.reply.image
  - name: ffmpeg
    workerClass: org.gytheio.content.transform.ffmpeg.FfmpegContentTransformerWorker
    enabled: true
    requestQueue: alfresco.transform.request.video
    replyQueue: alfresco.transform.reply.video
  - name: hash
    workerClass: org.gytheio.content.hash.javase.JavaSeContentHashWorker
    enabled: true
    requestQueue: alfresco.hash.request
    replyQueue: alfresco.hash.reply

server:
    applicationConnectors:
      - type: http
        port: 8888
    adminConnectors:
      - type: http
        port: 8889

version: ${project.version} (${buildNumber})

logging:
    loggers:
        "org.gytheio": DEBUG